### PR TITLE
Added CONTRIBUTING.md with standard rules

### LINKED ISSUE #12: Add contribution.md

### PR DESCRIPTION
**Pull request by rimijoker**
Resolves #12 
I have added the basic template for CONTRIBUTING.md
If you want me to add something more, please let me know @D3v3sh5ingh  🙂

### CODE REVIEW

**Comment by D3v3sh5ingh** [comment]
Can you also brief about the steps of contributing code i.e proper indented code, with Sample input-output and about originality of code.

**Comment by rimijoker** [comment]
> Can you also brief about the steps of contributing code i.e proper indented code, with Sample input-output and about originality of code

Sure @D3v3sh5ingh , is there a particular formatter/extension which you use to format the code in this project?

**Comment by D3v3sh5ingh** [comment]
> > Can you also brief about the steps of contributing code i.e proper indented code, with Sample input-output and about originality of code
> > Sure @D3v3sh5ingh , is there a particular formatter/extension which you use to format the code in this project?

No, the contributor may use any formatter for formatting the code, just mention that the code they are contributing is properly indented for code readability.

**Comment by D3v3sh5ingh** [comment]
Great work @rimijoker

**Pull request merged**
